pipeline {
    agent any

    stages {
        stage('Clean Containers') {
            steps {
                dir("logging") {
                    script {
                        try {
                            sh 'sudo docker compose -p logging --env-file linux.env down'
                        } finally {
                        }
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                dir("logging") {
                    sh 'sudo docker compose -p logging --env-file linux.env up -d'
                }
            }
        }
    }
}
