pipeline {
    agent any

    stages {
        stage('Clean Containers') {
            steps {
                script {
                    try {
                        sh 'sudo docker compose -p logging --env-file logging/linux.env down'
                    } finally {
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'sudo docker compose -p logging --env-file logging/linux.env up -d'
            }
        }
    }
}
